spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mircoservices
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:/db
    check-location: false
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
server:
  servlet:
    context-path: /uaa
  port: 5000
