spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mircoservices
    username: postgres
    password: postgres

server:
  servlet:
    context-path: /uaa
  port: 5000
