hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      serviceId: auth-service
      stripPrefix: false
      sensitiveHeaders:

    notification-service:
      path: /notifications/**
      serviceId: notification-service

    uuid:
      path: /uuid/**
      serviceId: uuid

    scheduler-service:
      path: /scheduler/**
      serviceId: scheduler-service

    information-service:
      path: /information/**
      serviceId: information-service

server:
  port: 4000
